export const GET_FAKE_ANNOUNCEMENT = "GET_FAKE_ANNOUNCEMENT";
export const GET_FAKE_QUIZZES = "GET_FAKE_QUIZZES";
export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const GET_QUIZZES = "GET_QUIZZES";
export const GET_ERROR = "GET_ERROR";
